version: '3.8'

services:
  yii2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:80"
    volumes:
      - .:/var/www/html
    networks:
      - appnet

networks:
  appnet:
