# Gunakan image Yii2 + PHP 7.4 + Apache
FROM yiisoftware/yii2-php:7.4-apache

# Set folder kerja di container
WORKDIR /var/www/html

# Copy semua source code ke container
COPY . /var/www/html

# Install ekstensi PHP yang dibutuhkan
RUN docker-php-ext-install pdo pdo_mysql \
    && a2enmod rewrite

# Ubah permission supaya web server bisa akses
RUN chown -R www-data:www-data /var/www/html
